### ISSUE TITLE
panicked at `already borrowed: BorrowMutError`

### ISSUE THREAD

**Issue by clangenb** [paritytech/environmental#7]
When running benchmarks, we are getting the following error, and we have problems finding the issue, we never had any problems under normal load. The potential causes coming to my mind is a potentially deep nesting of `with` calls due to access from different threads. This is how we use it: https://github.com/integritee-network/sgx-runtime/blob/7249cad5f43f73f2fc8f676a6a2435f057962b73/substrate-sgx/sp-io/src/lib.rs#L109

```
thread '' panicked at 'already borrowed: BorrowMutError', /home/sproll/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.1.3/src/lib.rs:142:41
note: Call backtrace::enable_backtrace with 'PrintFormat::Short/Full' for a backtrace.
fatal runtime error: failed to initiate panic, error 5
```

Do you have any idea, what it could be?

**Comment by haerdib** [comment]
In case someone else runs into this: The root problem was that we've run the library inside a `no_std` environment (intel sgx enclave to be precise), but in a multithreaded one. The `local_key` implementation of https://github.com/paritytech/environmental/blob/master/src/local_key.rs#L26 does not seem to be able to handle that.

In our case, the solution was to use the sgx provided `local_key` implementation instead.

**Comment by clangenb** [comment]
I guess I will close this issue, as this is the expected behaviour. Thanks for investigating!
